15. Temas interdisciplinarios

●	¿Las ciudades con mayor contaminación presentan tasas más altas de enfermedades respiratorias?

●	¿Existe una relación entre la desigualdad socioeconómica y el rendimiento escolar?

●	¿La urbanización se asocia con niveles más altos de contaminación?

●	¿Las regiones con mayor desarrollo económico presentan un mejor desempeño educativo?

●	¿El nivel de ingreso predice el acceso a la educación superior?



Links para esta pregunta.

-https://observatorio.ministeriodesarrollosocial.gob.cl/encuesta-casen-2022

- https://censo2024.ine.gob.cl/resultados/?utm_source

In [3]:
import pandas as pd        # pandas: librería principal para manipular tablas de datos (DataFrames)
import numpy as np         # numpy: librería para operaciones matemáticas y manejo de arreglos numéricos
import matplotlib.pyplot as plt  # matplotlib.pyplot: módulo para crear gráficos y visualizaciones
import seaborn as sns      # seaborn: librería de visualización de alto nivel, construida sobre matplotlib

In [30]:
import pandas as pd

import pandas as pd

idps2m = pd.read_csv("idps2m2022_rbd_dim_final.csv", sep=";", encoding="latin1")
idps4b = pd.read_csv("idps4b2022_rbd_dim_final.csv", sep=";", encoding="latin1")
casenresumen = pd.read_stata("Base de datos provincia y comuna Casen 2022 STATA.dta")
caseninfo = pd.read_excel("Libro_de_codigos_Casen_2022_prov_comuna.xlsx")
casenfull = pd.read_stata("casen_2022.dta", convert_categoricals= False)

In [40]:
casenfull.columns.tolist()

['id_vivienda',
 'folio',
 'id_persona',
 'region',
 'region_geo',
 'area',
 'cod_upm',
 'nse',
 'estrato',
 'hogar',
 'expr',
 'expr_osig',
 'varstrat',
 'varunit',
 'fecha_entrev',
 'p1',
 'p2',
 'p3',
 'p4',
 'p9',
 'p10',
 'p11',
 'tot_per_h',
 'h1',
 'edad',
 'mes_nac_nna',
 'ano_nac_nna',
 'sexo',
 'pco1_a',
 'pco1_b',
 'pco1',
 'h5_cp',
 'h5_sp',
 'h5b_1_1',
 'h5b_1_2',
 'h5a_2',
 'h5b_2_1',
 'h5b_2_2',
 'h5a_3',
 'h5b_3_1',
 'h5b_3_2',
 'h5a_4',
 'h5b',
 'ecivil',
 'h5_10',
 'h5_1a',
 'h5_1b',
 'h5_20',
 'h5_2',
 'n_nucleos',
 'nucleo',
 'nucleo_ajustado',
 'pco2_a',
 'pco2_b',
 'pco2',
 'h7a',
 'h7b',
 'h7c',
 'h7d',
 'h7e',
 'h7f',
 'informante',
 'e1',
 'e3',
 'e4a',
 'e4a_esp',
 'e5a',
 'e5a_esp',
 'e5b',
 'e6a_asiste',
 'e6a_no_asiste',
 'e6a',
 'e6b_asiste',
 'e6b_no_asiste',
 'e6b',
 'e6c_completo',
 'e6d_preg',
 'e6d_postg',
 'e7',
 'cinef13_area',
 'cinef13_subarea',
 'e8',
 'e9nom',
 'e9dir',
 'e9com_cod',
 'e9pais_cod',
 'e9rbd',
 'e9rbd_sup',
 'e9dv',
 'e9depen',
 'e10',
 'e11',
 'e12a',
 'e12b',
 'e12c',
 'e12d',
 'e12e',
 'e13a',
 'e13b_1',
 'e13b_2',
 'e13b_3',
 'e13b_4',
 'e13b_5',
 'e13b_6',
 'e13b_7',
 'e13b_8',
 'e13b_9',
 'e13b_10',
 'e13b_11',
 'e13b1',
 'e13b2',
 'e13b_esp1',
 'e13b_esp2',
 'e14a',
 'e14b',
 'e14c',
 'e14d',
 'e14e',
 'e16',
 'e18',
 'o1',
 'o2',
 'o3',
 'o4',
 'o5',
 'o6',
 'o7',
 'o7_esp',
 'o8',
 'o9a',
 'o9b',
 'oficio1_08',
 'oficio4_08',
 'o10',
 'o11',
 'o12',
 'o14',
 'o15',
 'o16',
 'o19',
 'o18',
 'o20',
 'o21',
 'o22',
 'o23',
 'o24',
 'rama1_sub_rev4',
 'rama4_sub_rev4',
 'rama1',
 'rama4',
 'o25',
 'o26a',
 'o26b',
 'o26c',
 'o26d',
 'o28a_hr',
 'o28a_min',
 'o28b',
 'o28c',
 'o28c_esp',
 'o28d',
 'o28e',
 'o29',
 'o30',
 'o31',
 'o32',
 'o32_esp',
 'o32b',
 'y1',
 'y2_dias',
 'y2_hrs',
 'y3a_preg',
 'y3b_preg',
 'y3c_preg',
 'y3d_preg',
 'y3e_preg',
 'y3f_preg',
 'y3a',
 'y3ap',
 'y3b',
 'y3bp',
 'y3c',
 'y3cp',
 'y3d',
 'y3dp',
 'y3e',
 'y3ep',
 'y3f_esp',
 'y3f',
 'y3fp',
 'y4a_preg',
 'y4b_preg',
 'y4c_preg',
 'y4d_preg',
 'y4a',
 'y4b',
 'y4c',
 'y4d_esp',
 'y4d',
 'y5a_preg',
 'y5b_preg',
 'y5c_preg',
 'y5d_preg',
 'y5e_preg',
 'y5f_preg',
 'y5g_preg',
 'y5h_preg',
 'y5i_preg',
 'y5j_preg',
 'y5k_preg',
 'y5l_preg',
 'y5a',
 'y5b',
 'y5c',
 'y5d',
 'y5e',
 'y5f',
 'y5g',
 'y5h',
 'y5i',
 'y5j',
 'y5k',
 'y5l',
 'y6',
 'y7',
 'y8',
 'y9',
 'y10',
 'y11_preg',
 'y11',
 'y12a_preg',
 'y12a',
 'y12b_preg',
 'y12b',
 'y13a_preg',
 'y13a',
 'y13b_preg',
 'y13b',
 'y13c_preg',
 'y13c',
 'y14a_preg',
 'y14a',
 'y14b_preg',
 'y14b',
 'y14c_preg',
 'y14c',
 'y15a_preg',
 'y15a',
 'y15b_preg',
 'y15b',
 'y15c_preg',
 'y15c',
 'y16a_preg',
 'y16a',
 'y16b_preg',
 'y16b',
 'y17_preg',
 'y17',
 'y18a_preg',
 'y18a',
 'y18b_preg',
 'y18b',
 'y18c_preg',
 'y18c',
 'y18d_preg',
 'y18d_esp',
 'y18d',
 'y19',
 'y19t',
 'y19n',
 'y20a',
 'y20b',
 'y20c',
 'y20d',
 'y20e',
 'y20amonto',
 'y20bmonto',
 'y20cmonto',
 'y20dmonto',
 'y20emonto',
 'y21_canasta',
 'y22_preg',
 'y22',
 'y22amonto',
 'y22bmonto',
 'y22cmonto',
 'y22dmonto',
 'y23a_preg',
 'y23a',
 'y23b',
 'y23c',
 'y23bmonto',
 'y23cmonto',
 'y24_preg',
 'y24',
 'y25a_preg',
 'y25a',
 'y25amonto',
 'y25b_preg',
 'y25b',
 'y25bmonto',
 'y25c',
 'y25cmonto',
 'y25d',
 'y25dmonto',
 'y25ep',
 'y25e',
 'y25fp',
 'y25f',
 'y25g_preg',
 'y25g',
 'y25h_preg',
 'y25hp',
 'y25h',
 'y25i_preg',
 'y25imonto',
 'y25ip',
 'y25j_preg',
 'y25j',
 'y25jmonto',
 'y26d_hog',
 'y26d_preg',
 'y26d_integrantes',
 'y26d_monto',
 'y27_preg',
 'y27_esp',
 'y27',
 'y28_1b',
 'y28_1c',
 'y28_1d',
 'y28_1dmonto',
 'y28_1e',
 'y28_1f',
 'y28_1g',
 'y28_1h',
 'y28_1i',
 'y28_1j',
 'y28j_esp',
 'y28_2b1',
 'y28_2b2',
 'y28_3b',
 'y28_4b',
 'y28_1c1',
 'y28_1c2',
 'y28_1c2monto',
 'y28_2c1',
 'y28_2c2',
 'y28_2c',
 'y28_3c',
 'y28_4c',
 'y28_2e1',
 'y28_2e2',
 'y28_3e',
 'y28_4e',
 'y28_2f',
 'y28_3f',
 'y28_4f',
 'y28_1g1',
 'y28_2g1',
 'y28_2g2',
 'y28_2g',
 'y28_3g',
 'y28_4g',
 'y28_2h',
 'y28_3h',
 'y28_4h',
 'y28_1i1',
 'y28_2i1',
 'y28_2i2',
 'y28_2i',
 'y28_2j',
 'y28_3j',
 'y28_4j',
 's2',
 's2c',
 's3_1',
 's3_2',
 's3_3',
 's3_4',
 's3_5',
 's3_6',
 's3_7',
 's3_8',
 's3_88',
 's3a1',
 's3a2',
 's4',
 's5',
 's6',
 's7',
 's7_meses',
 's8',
 's9a',
 's9b',
 's10',
 's11a',
 's11b',
 's12',
 's13',
 's13_fonasa',
 's15',
 's16',
 's17',
 's17b',
 's18',
 's18_esp',
 's19a',
 's19b',
 's19c',
 's19d',
 's19e',
 's20a_preg',
 's20a',
 's20b',
 's21a_preg',
 's21a',
 's21b',
 's22a_preg',
 's22a',
 's22b',
 's23a_preg',
 's23a',
 's23b',
 's24a_preg',
 's24a',
 's24b',
 's25a1_preg',
 's25b1',
 's25a2_preg',
 's25b2',
 's26a',
 's26b_1',
 's26b_2',
 's26b_3',
 's26b_4',
 's26b_5',
 's26b_6',
 's26b_7',
 's26b_8',
 's26b_88',
 's26b_esp',
 's26u',
 's26c',
 's27a',
 's27b',
 's27c',
 's28',
 's28_esp',
 's29',
 's30',
 's30_esp',
 's31_1',
 's31_2',
 's31_3',
 's31_4',
 's31_5',
 's31_6',
 's31_7',
 's32a',
 's32b',
 's32c',
 's32d',
 's32e',
 's32f',
 's32g',
 's32h',
 's32i',
 's32j',
 's33a',
 's33b',
 's33c',
 's33d',
 's33e',
 's33f',
 's33g',
 's33h',
 's33i',
 's33j',
 's34a',
 's34b',
 's34c',
 'r1a',
 'r1a_esp',
 'r1a_esp_cod',
 'r1b',
 'r1b_comuna_esp',
 'r1b_comuna_esp_cod',
 'r1b_pais_esp',
 'r1b_pais_esp_cod',
 'r1c',
 'r1cp',
 'r2',
 'r2_comuna_esp',
 'r2_comuna_esp_cod',
 'r2_pais_esp',
 'r2_pais_esp_cod',
 'r3',
 'r4',
 'r5',
 'r6',
 'r7a',
 'r7b',
 'r7c',
 'r7d',
 'r7e',
 'r7f',
 'r7g',
 'r7h',
 'r7i',
 'r7j',
 'r7k',
 'r8a',
 'r8b',
 'r8c',
 'r8d',
 'r8e',
 'r8f',
 'r8g',
 'r8h',
 'r9a',
 'r9b',
 'r9c',
 'r9d',
 'r9e',
 'r9f',
 'r9g',
 'r9h',
 'r9i',
 'r9j',
 'r9k',
 'r9l',
 'r9m',
 'r9n',
 'r9o',
 'r9p',
 'r9q',
 'r9r',
 'r9s',
 'r9t',
 'r9_esp',
 'r11',
 'r12a',
 'r12b',
 'r13a',
 'r13b',
 'r14',
 'r15',
 'r17a',
 'r17b',
 'r17c',
 'r17d',
 'r17e',
 'r18',
 'v1',
 'v2',
 'v3',
 'v4',
 'v5',
 'v6',
 'v7',
 'v9',
 'v10',
 'v11_o1',
 'v11_o2',
 'v12',
 'v12mt',
 'v13',
 'v13_propia',
 'v13_arrendada',
 'v13_cedida',
 'v13b_1',
 'v13b_2',
 'v13b_3',
 'v13b_4',
 'v13b_5',
 'v13b_6',
 'v13b_7',
 'v14',
 'v15',
 'v16',
 'v17',
 'v18',
 'v19',
 'v20',
 'v20_esp',
 'v20_red',
 'v21',
 'v22',
 'v23',
 'v23_sistema',
 'v23_cajon',
 'v24',
 'v25',
 'v26',
 'v27a',
 'v27b',
 'v28',
 'v29a',
 'v29b',
 'v30',
 'v31',
 'v32',
 'v33',
 'v34a',
 'v34b',
 'v34c',
 'v35a',
 'v35b',
 'v35c',
 'v35d',
 'v35e',
 'v35f',
 'v35g',
 'v35h',
 'v35i',
 'v36a',
 'v36b',
 'v36c',
 'v36d',
 'v36e',
 'v37a',
 'v37b',
 'v37c',
 'v37d',
 'v37e',
 'v37f',
 'v37g',
 'v38',
 'os_presente',
 'os1',
 'os1_esp',
 'genero',
 'genero_esp',
 'trans',
 'y0101',
 'y0301',
 'y0302',
 'y0303',
 'y0304',
 'y0305',
 'y0306',
 'y0401',
 'y0402',
 'y0403',
 'y0404',
 'y0501',
 'y0502',
 'y0503',
 'y0504',
 'y0505',
 'y0506',
 'y0507',
 'y0508',
 'y0509',
 'y0510',
 'y0511',
 'y0512',
 'yosa',
 'y0701',
 'y0801',
 'y0901',
 'yosi',
 'y1101',
 'yre1',
 'yama',
 'ymes',
 'yfa1',
 'yfa2',
 'ytro',
 'yta1',
 'yta2',
 'ydes',
 'yah1',
 'yah2',
 'yrut',
 'yre2',
 'yre3',
 'yac2',
 'yids',
 'ydon',
 'ydim',
 'yotr',
 'yfam',
 'y2001',
 'y2002',
 'y2003',
 'y2004',
 'y2005',
 'y2101',
 'y2201',
 'y2202',
 'y2203',
 'y2204',
 'y2301',
 'y2302',
 'y2303',
 'y2401',
 'y2501',
 'y2502',
 'y2503',
 'y2504',
 'y2505',
 'y2506',
 'y2507',
 'y2508p',
 'y2508',
 'y2509',
 'y2510',
 'y2604',
 'y2701',
 'y2804',
 'y280201',
 'y280202',
 'y280101',
 'y280301',
 'y280302',
 'y2803',
 'yinv0101',
 'yinv0102',
 'yinv02',
 'ymon0101',
 'ymon0102',
 'ymon02',
 'yorf',
 'yesp0101',
 'yesp0102',
 'yesp',
 'yotp',
 'yaut',
 'ysub1',
 'ysub2',
 'ysub',
 'ytot',
 'y0101h',
 'y0301h',
 'y0302h',
 'y0303h',
 'y0304h',
 'y0305h',
 'y0306h',
 'y0401h',
 'y0402h',
 'y0403h',
 'y0404h',
 'y0501h',
 'y0502h',
 'y0503h',
 'y0504h',
 'y0505h',
 'y0506h',
 'y0507h',
 'y0508h',
 'y0509h',
 'y0510h',
 'y0511h',
 'y0512h',
 'yosah',
 'y0701h',
 'y0801h',
 'y0901h',
 'yosih',
 'y1101h',
 'yre1h',
 'yamah',
 'ymesh',
 'yfa1h',
 'yfa2h',
 'ytroh',
 'yta1h',
 'yta2h',
 'ydesh',
 'yah1h',
 'yah2h',
 'yruth',
 'yre2h',
 'yre3h',
 'yac2h',
 'yidsh',
 'ydonh',
 'ydimh',
 'yotrh',
 'yfamh',
 'y2001h',
 'y2002h',
 'y2003h',
 'y2004h',
 'y2005h',
 'y2101h',
 'y2201h',
 'y2202h',
 'y2203h',
 'y2204h',
 'y2301h',
 'y2302h',
 'y2303h',
 'y2401h',
 'y2501h',
 'y2502h',
 'y2503h',
 'y2504h',
 'y2505h',
 'y2506h',
 'y2507h',
 'y2508h',
 'y2509h',
 'y2510h',
 'y2604h',
 'y2701h',
 'y2804h',
 'y280201h',
 'y280202h',
 'y280101h',
 'y280301h',
 'y280302h',
 'y2803h',
 'yinv0101h',
 'yinv0102h',
 'yinv02h',
 'ymon0101h',
 'ymon0102h',
 'ymon02h',
 'yorfh',
 'yesp0101h',
 'yesp0102h',
 'yesph',
 'yotph',
 'yauth',
 'ysub1h',
 'ysub2h',
 'ysubh',
 'yaimh',
 'ytoth',
 'y0101c',
 'y0701c',
 'y280201c',
 'y280301c',
 'y2803c',
 'yautcor',
 'ytotcor',
 'y0101ch',
 'y0701ch',
 'y280201ch',
 'y280301ch',
 'y2803ch',
 'yautcorh',
 'yaimcorh',
 'ytotcorh',
 'ymonecorh',
 'no_arrienda',
 'nae',
 'yae',
 'li',
 'lp',
 'pobreza',
 'yae_2013',
 'li_2013',
 'lp_2013',
 'pobreza_2013',
 'yoprcor',
 'yoprcorh',
 'yoautcor',
 'yoautcorh',
 'ytrabajocor',
 'ytrabajocorh',
 'ypchautcor',
 'ypchtrabcor',
 'ypchtotcor',
 'ypchmonecor',
 'dau',
 'qaut',
 'dautr',
 'qautr',
 'pobreza_severa',
 'hh_d_asis',
 'hh_d_rez',
 'hh_d_esc',
 'hh_d_ape',
 'hh_d_acc',
 'hh_d_ali',
 'hh_d_contprev',
 'hh_d_dpf',
 'hh_d_actsub',
 'hh_d_inf',
 'hh_d_jub',
 'hh_d_cui',
 'hh_d_defcuali',
 'hh_d_defcuanti',
 'hh_d_accesi',
 'hh_d_medio',
 'hh_d_apoyo',
 'hh_d_tsocial',
 'hh_d_conec',
 'hh_d_seg',
 'pobreza_multi',
 'hh_d_asis_2015',
 'hh_d_rez_2015',
 'hh_d_esc_2015',
 'hh_d_mal_2015',
 'hh_d_prevs_2015',
 'hh_d_acc_2015',
 'hh_d_act_2015',
 'hh_d_cot_2015',
 'hh_d_jub_2015',
 'hh_d_hacina_2015',
 'hh_d_estado_2015',
 'hh_d_habitab_2015',
 'hh_d_servbas_2015',
 'hh_d_medio_2015',
 'hh_d_equipo_2015',
 'hh_d_tiempo_2015',
 'hh_d_accesi_2015',
 'hh_d_entorno_2015',
 'hh_d_hapoyo_2015',
 'hh_d_part_2015',
 'hh_d_tsocial_2015',
 'hh_d_seg_2015',
 'hh_d_appart_2015',
 'pobreza_multi_2015',
 'pobreza_multi_4d',
 'disc_wg',
 'analfabetismo',
 'agnoesc',
 'esc',
 'desercion',
 'rezagobasica',
 'rezagomedia',
 'asiste',
 'educc',
 'depen',
 'activ',
 'asalariado',
 'contrato',
 'cotiza',
 'depen_fun',
 'depen_grado',
 'persona_cuidada',
 'cuidador',
 'lugar_nac',
 'pueblos_indigenas',
 'n_ocupados',
 'n_desocupados',
 'n_inactivos',
 'numper',
 'numnuc',
 'men18c',
 'may60c',
 'tipohogar',
 'tot_hog',
 'ind_hacina',
 'ind_san',
 'ind_tip',
 'ten_viv',
 'ten_viv_f',
 'allega_ext',
 'allega_int',
 'ind_mat',
 'ind_estado',
 'ind_cal_glob',
 'nucleo_jefe']

In [44]:
cols = [
    "folio", "id_persona",
    "region", "region_geo", "area",
    "nse",
    "ypchtotcor", "qaut", "dau",
    "pobreza", "pobreza_multi",
    "esc", "agnoesc",
    "ind_hacina",
    "expr"
]

casen_reducido = casenfull[cols].copy()

print(casen_reducido.shape)
print(casen_reducido.head())
print(casen_reducido.info())
print(casen_reducido.isnull().sum().sort_values(ascending=False))
casen_reducido.to_excel("casen_reducido.xlsx", index=False)

(202231, 15)
       folio  id_persona  region  region_geo  area  nse  ypchtotcor  qaut  \
0  100090101           1      16          10     2    4    336965.0   2.0
1  100090101           2      16          10     2    4    336965.0   2.0
2  100090101           3      16          10     2    4    336965.0   2.0
3  100090201           1      16          10     2    4    104548.0   1.0
4  100090201           2      16          10     2    4    104548.0   1.0

   dau  pobreza  pobreza_multi   esc  agnoesc  ind_hacina  expr
0  3.0      3.0            0.0   1.0      1.0           1    43
1  3.0      3.0            0.0   4.0      4.0           1    43
2  3.0      3.0            0.0  15.0     15.0           1    44
3  1.0      1.0            1.0   NaN      NaN           1    51
4  1.0      1.0            1.0  12.0     12.0           1    51
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202231 entries, 0 to 202230
Data columns (total 15 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   folio          202231 non-null  int32
 1   id_persona     202231 non-null  int8
 2   region         202231 non-null  int8
 3   region_geo     202231 non-null  int8
 4   area           202231 non-null  int8
 5   nse            202231 non-null  int8
 6   ypchtotcor     202111 non-null  float64
 7   qaut           202111 non-null  float64
 8   dau            202111 non-null  float64
 9   pobreza        202111 non-null  float64
 10  pobreza_multi  189888 non-null  float64
 11  esc            165248 non-null  float64
 12  agnoesc        201078 non-null  float64
 13  ind_hacina     202231 non-null  int8
 14  expr           202231 non-null  int16
dtypes: float64(7), int16(1), int32(1), int8(6)
memory usage: 13.1 MB
None
esc              36983
pobreza_multi    12343
agnoesc           1153
qaut               120
ypchtotcor         120
dau                120
pobreza            120
nse                  0
area                 0
region_geo           0
region               0
folio                0
id_persona           0
ind_hacina           0
expr                 0
dtype: int64

In [17]:
idps2m.head()

,rbd,agno,grado,ind,dim,prom,nom_rbd,cod_reg_rbd,nom_reg_rbd,cod_pro_rbd,nom_pro_rbd,cod_com_rbd,nom_com_rbd,nom_deprov_rbd,cod_depe2,cod_grupo,cod_rural_rbd,fecha_bbdd,codigo_bdd
0,1,2022,2,AM,AA,68.0,LICEO POLITECNICO ARICA,15,DE ARICA Y PARINACOTA,151,ARICA,15101,ARICA,Arica,4,1.0,1,20240528,final20240603v1
1,1,2022,2,AM,ME,78.0,LICEO POLITECNICO ARICA,15,DE ARICA Y PARINACOTA,151,ARICA,15101,ARICA,Arica,4,1.0,1,20240528,final20240603v1
2,1,2022,2,CC,AO,81.0,LICEO POLITECNICO ARICA,15,DE ARICA Y PARINACOTA,151,ARICA,15101,ARICA,Arica,4,1.0,1,20240528,final20240603v1
3,1,2022,2,CC,AR,68.0,LICEO POLITECNICO ARICA,15,DE ARICA Y PARINACOTA,151,ARICA,15101,ARICA,Arica,4,1.0,1,20240528,final20240603v1
4,1,2022,2,CC,AS,77.0,LICEO POLITECNICO ARICA,15,DE ARICA Y PARINACOTA,151,ARICA,15101,ARICA,Arica,4,1.0,1,20240528,final20240603v1

In [25]:
casen.head()

       folio  id_persona provincia  comuna  expp  expc
0  100090101           1   Punilla  Ñiquén    51    52
1  100090101           2   Punilla  Ñiquén    50    53
2  100090101           3   Punilla  Ñiquén    51    52
3  100090201           1   Punilla  Ñiquén    51    52
4  100090201           2   Punilla  Ñiquén    50    52

In [24]:
prom_comuna_2m = idps2m.groupby("cod_com_rbd")["prom"].mean().reset_index()
prom_comuna_2m.columns = ["comuna", "promedio_idps_2m"]
display(prom_comuna_2m)

     comuna  promedio_idps_2m
0      1101         73.861244
1      1107         76.347594
2      1401         77.272727
3      1402         79.909091
4      1403         75.272727
..      ...               ...
327   16301         78.818182
328   16302         74.977273
329   16303         77.818182
330   16304         68.818182
331   16305         82.000000

[332 rows x 2 columns]

In [26]:
casen.columns.tolist()

['folio', 'id_persona', 'provincia', 'comuna', 'expp', 'expc']